### ISSUE TITLE
Repository naam en omschrijving

### ISSUE THREAD

**Issue by sasjakoning** [Inevdhoven/web-app-from-scratch-2223#1]
Je hebt een omschrijving toegevoegd aan je repository maar deze is nog best schaars en zegt weinig over jouw project. Verder is het misschien leuk om jouw repository naam te veranderen naar de naam van je app?

**Comment by Inevdhoven** [comment]
Ik ga meer informatie toevoegen over mijn project en ik ga nadenken over hoe ik mijn repository ga noemen.

**Comment by Inevdhoven** [comment]
Ik heb de naam en beschrijving aangepast, zodat het nu beter bij het project past.
