### ISSUE TITLE
Afbeelding in detailpagina responsive maken

### ISSUE THREAD

**Issue by K3A101** [Inevdhoven/web-app-from-scratch-2223#13]

**Comment by Inevdhoven** [comment]
Ik ga kijken of ik ervoor kan zorgen dat de afbeelding of volledig in beeld is of dat je erop kan klikken en deze dan volledig kan bekijken

**Comment by Inevdhoven** [comment]
Ik heb dit nu opgelost door een icoontje toe te voegen aan de detailpagina waar je op kan klikken om de afbeelding in zijn geheel passend op het scherm te bekijken.
