### ISSUE TITLE
Detailpagina niet beschikbaar na zoeken

### ISSUE THREAD

**Issue by PipHarsveld** [Inevdhoven/web-app-from-scratch-2223#17]
Als je naar de detailpagina wil van een kunstwerk dat je via de zoekfunctie gevonden hebt, krijg je een 404 error. Ik denk dus dat dit nog niet goed is doorgelinkt.

**Comment by Inevdhoven** [comment]
Dit heb ik toevallig net gepusht en zou als het goed is nu opgelost moeten zijn :)
